src/onelogin/saml2/xml_utils.py

This patch makes make_root, make_child and cleanup_namespaces static in order to prevent this error that we had on python2
```
Environment:
Request Method: GET
Request URL: http://localhost:8000/saml/logout/
Django Version: 1.8.3
Python Version: 2.7.10
Installed Applications:
(u'flat',
u'django.contrib.admin',
u'django.contrib.auth',
u'django.contrib.contenttypes',
u'django.contrib.sessions',
u'django.contrib.messages',
u'django.contrib.staticfiles',
u'django.contrib.sites',
u'django_extensions')
Installed Middleware:
(u'django.contrib.sessions.middleware.SessionMiddleware',
u'corsheaders.middleware.CorsMiddleware',
u'django.middleware.common.CommonMiddleware',
u'django.middleware.csrf.CsrfViewMiddleware',
u'django.contrib.auth.middleware.AuthenticationMiddleware', …
```

Fix logout on Python 2

---

src/onelogin/saml2/response.py

Seems like we should be returning an empty list instead of `[None]` when parsing the below in the SAML Response:
```
<saml:AudienceRestriction>
<saml:Audience/>
</saml:AudienceRestriction>
```

Return empty list when there are no audience values

---

README.md

It took a significant amount of time for us to troubleshoot this, and although there's a few stackoverflow questions and blog posts with descriptions about solving the problem (none of which we could get working), the buildpack is the simplest approach.

Add information about getting the demos up and running on Heroku

---

src/onelogin/saml2/auth.py
src/onelogin/saml2/logout_request.py
src/onelogin/saml2/utils.py
tests/src/OneLogin/saml2_tests/utils_test.py

Per the suggestions in https://github.com/onelogin/python3-saml/issues/13, this should accomplish plumbing through NameQualifier into the saml Logout Request object.

passing NameQualifier through to logout request

---

src/onelogin/saml2/idp_metadata_parser.py
tests/src/OneLogin/saml2_tests/idp_metadata_parser_test.py

This tackles the following issues:
* https://github.com/onelogin/python3-saml/issues/17
* https://github.com/onelogin/python3-saml/issues/18
* https://github.com/onelogin/python3-saml/issues/19
* https://github.com/onelogin/python3-saml/issues/20
@pitbulk I hope these are good for you :-) While I needed to touch the tests quite a lot, this new behavior should still be backwards-compatible.

IdP metadata parser/merger adjustments

---

src/onelogin/saml2/metadata.py
src/onelogin/saml2/settings.py

Getting Unix time with strftime("%s") will only work on POSIX platforms, so not on Windows. time() is fine for both.

Fixes Windows specific Unix date formatting bug

---

README.md

This PR fixes:
- some typos (also removes some unneeded whitespace characters)
- consistency issues with quotes in json samples (now everything uses double quotes)
- one minor issue where `serviceName` was incorrectly capitalized in the json sample

Fix typos and json sample code in documentation

---

README.md
src/onelogin/saml2/response.py
tests/settings/settings6.json
tests/src/OneLogin/saml2_tests/response_test.py

Fixed support for formated fingerprints as discussed in #44.
Also added tests and fixed a small typo in the README.md

Fixed bug with formated cert fingerprints

---

src/onelogin/saml2/response.py

This part of the code was skipped for some reasons from the equivalent
commit in python-saml

Properly use multi certs when validating auth response signature. Fixes #58

---

src/onelogin/saml2/auth.py
src/onelogin/saml2/logout_response.py
src/onelogin/saml2/response.py
tests/src/OneLogin/saml2_tests/auth_test.py

I tried to follow the pattern used in php-saml.
This is an attempt to fix #62

Add get_last_message_id and get_last_assertion_id

---

README.md

Fixes https://github.com/onelogin/python3-saml/issues/71
This adds documentation for the 4 undocumented request parameters.
I'm a little unclear on the intended use of the `request_uri` and `query_string` parameters (used [here](https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/utils.py#L340-L357)), but I _think_ I've documented those correctly.
This also tweaks several headings throughout the README that were failing to render with GitHub-flavored markdown because they were missing a leading space, for example:
```
####This Heading Doesn't Render
```

Documented Advanced Request Parameters

---

demo-django/demo/settings.py
demo-django/demo/urls.py
demo-django/demo/views.py
demo-django/requirements.txt

I've updated the demo-django example to use Django 1.11. This mostly involved rewriting some settings and updating deprecated functions.

Update demo-django to Django 1.11

---

src/onelogin/saml2/utils.py
tests/src/OneLogin/saml2_tests/metadata_test.py
tests/src/OneLogin/saml2_tests/utils_test.py

The `OneLogin_Saml2_Utils.add_sign` method added the `Signature` element inside the first element of the `EntityDescriptor` when metadata signing was enabled.
The SAML 2 metadata schema says that the signature tag must be the first element inside the `EntityDescriptor`.

Fix signature tag position in the SP metadata

---

src/onelogin/saml2/constants.py
src/onelogin/saml2/xml_utils.py
tests/pep8.rc

Fix for: https://github.com/onelogin/python3-saml/issues/76
This PR overrides the `OneLogin_Saml2_XML` static method `cleanup_namspaces`, which is directly invoking `etree.cleanup_namespaces`. I added a whitelist of namespaces that should not be cleaned from an element before serialization into XML. This preserves the `xmlns:xs` namespace that's specifically needed to validate the schema of a SAML Response's attributes.
I also added some additional namespace prefix constants (now grouped with the other namespace constants) in `OneLogin_Saml2_Constants`.

Preserve xmlns:xs namespace when signing and serializing responses

---

.travis.yml
demo-django/demo/settings.py
demo-django/demo/views.py
demo-django/demo/wsgi.py
setup.cfg
setup.py
src/onelogin/saml2/idp_metadata_parser.py
src/onelogin/saml2/utils.py
tests/pep8.rc
tests/src/OneLogin/saml2_tests/authn_request_test.py
tests/src/OneLogin/saml2_tests/idp_metadata_parser_test.py
tests/src/OneLogin/saml2_tests/logout_request_test.py
tests/src/OneLogin/saml2_tests/logout_response_test.py

Applying the lessons learned from onelogin/python-saml#246
Add Python 3.7 to the testing.
Add [flake8](http://flake8.pycqa.org) which is a superset of __pycodestyle__ (fka pep8) plus __pyflakes__ plus McCabe complexity analysis.  This PR runs all the same tests as the current pep8 and pyflakes plus it adds several new tests.  The numbers in __setup.cfg__ for __max-complexity__ and __max-line-length__ are really too high and should be something like __10__ and __127__ respectively.

TravisCI: Py3.7 & flake8 is a superset of pep8 and pyflakes

---

setup.py

Now that #124 is merged and Python 3.7 is passing the Travis tests.

setup.py: Add the Python 3.7 trove classifier for PyPI

---

src/onelogin/saml2/metadata.py
tests/src/OneLogin/saml2_tests/metadata_test.py

Wrong variable name caused FriendlyName to overwrite NameFormat in RequestedAttribute tags when creating AttributeConsumingService section of the metadata XML.

Fixed setting NameFormat attribute for AttributeValue tags

---

README.md

* Use `heroku buildpacks:add` instead of `:set` so existing buildpacks aren't overwritten
* Replace deprecated ABASystems' apt buildpack (redirects to uptick/heroku-buildpack-apt, which hasn't been updated in 3 years, forked from ddollar/heroku-buildpack-apt, which explicitly says it's deprecated) with Heroku's (https://github.com/heroku/heroku-buildpack-apt)
* Replace ABASystems' python buildpack with Heroku's (heroku/python)
Confirmed this works on Heroku. (Sorry for closing the previous PR - accident)

Update Heroku instructions

---

tests/data/metadata/metadata_settings1.xml

Make tests pass in 2020
moving this date beyond 2038 requires fixes on 32-bit systems to avoid errors:
```
File "/home/abuild/rpmbuild/BUILD/python3-saml-1.6.0/tests/src/OneLogin/saml2_tests/settings_test.py", line 560, in testValidateMetadata
self.assertEqual(len(settings.validate_metadata(xml)), 0)
File "/home/abuild/rpmbuild/BUILD/python3-saml-1.6.0/src/onelogin/saml2/settings.py", line 716, in validate_metadata
expire_time = OneLogin_Saml2_Utils.get_expire_time(cache_duration, valid_until)
File "/home/abuild/rpmbuild/BUILD/python3-saml-1.6.0/src/onelogin/saml2/utils.py", line 480, in get_expire_time
valid_until_time = OneLogin_Saml2_Utils.parse_SAML_to_time(valid_until)
File "/home/abuild/rpmbuild/BUILD/python3-saml-1.6.0/src/onelogin/saml2/utils.py", line 419, in parse_SAML_to_time …
```

Make tests pass in 2020

---

src/onelogin/saml2/logout_response.py
src/onelogin/saml2/response.py
tests/src/OneLogin/saml2_tests/response_test.py

Easier access for SP use to prevent replay attacks and match Responses to Requests

Added get_in_response_to method to Response and LogoutResponse classes

---

.travis.yml
changelog.md

Python3.4 is not supported anymore by lxml. Since lots of distribution handle python3.5 by default and because it breaks the CI, it looks obvious to drop it.

Drop python3.4 support

---

README.md

Fixes a typo in which the Assertion Consumer Service was erroniously referred to as the Attribute Consumer Service
See line 497 of https://www.oasis-open.org/committees/download.php/56783/sstc-saml-profiles-errata-2.0-wd-07-diff.pdf

Fix typo: Attribute Consumer Service -> Assertion Consumer Service

---

demo-flask/index.py

Unlike demo-django, samlUserdata isn't set in demo-flask's session which causes both index.html and attrs.html to always display login buttons and lack attributes, even when a user is logged in.

Add samlUserdata to demo-flask session

---

src/onelogin/saml2/auth.py
src/onelogin/saml2/logout_request.py
src/onelogin/saml2/response.py
src/onelogin/saml2/settings.py
tests/settings/settings10.json
tests/settings/settings9.json
tests/src/OneLogin/saml2_tests/response_test.py
tests/src/OneLogin/saml2_tests/settings_test.py

This is very trivial. But loading idp public certificate just like the sp certificates.

Load idp certs from file

---

src/onelogin/saml2/logout_request.py
src/onelogin/saml2/logout_response.py
src/onelogin/saml2/response.py
src/onelogin/saml2/utils.py
tests/src/OneLogin/saml2_tests/logout_request_test.py
tests/src/OneLogin/saml2_tests/logout_response_test.py
tests/src/OneLogin/saml2_tests/response_test.py
tests/src/OneLogin/saml2_tests/utils_test.py

PR to resolve: https://github.com/onelogin/python3-saml/issues/226. This PR resolves ignoring netloc case when comparing the Destination URL to the actual URL when validating SAML responses (per RFC 4343/7617)
Although a fix like this was suggested: https://github.com/onelogin/ruby-saml/blob/17fce0a6caa6282ebd51c6276d3a7b91138b8d24/lib/onelogin/ruby-saml/utils.rb#L284
The preferred change appears to be attempting to parse the both the expected and the actual url, converting the hostname to lowercase, and returning it as a string. This solution results in the fewest code changes. If the URL parsing fails, the original url is returned, so the backend behavior regresses to the current implementation.
I do wonder if we should be using:
```python
if not …
```

Resolved issue 226 with testing: Destination URL Comparison is now case-insensitive for netloc

---

src/onelogin/saml2/auth.py
src/onelogin/saml2/authn_request.py
src/onelogin/saml2/idp_metadata_parser.py
src/onelogin/saml2/logout_request.py
src/onelogin/saml2/metadata.py
src/onelogin/saml2/settings.py

As discussed in https://github.com/onelogin/python3-saml/issues/208#issuecomment-678099281, this PR makes it possible to override the request ID for an authentication request.
To make that easier in turn, this PR also "indirects" some of those classes by storing them as class attributes on the classes that use them, and similarly some methods that used to be staticmethods and called out to other staticmethods on the same class are now classmethods, to allow for overriding them in subclasses.

Overridability enhancements

---

demo_pyramid/demo_pyramid/views.py

This PR helps when running a reverse proxy in front of the pyramid demo by overriding `request.scheme` and `request.server_port` when the proper `X-Forwarded` headers are set.

Optionally modify request based on X-Forwarded headers in demo_pyramid

---

src/onelogin/saml2/logout_request.py

In 9fdb11d (which is included in v1.10.0), in addition to logout_response.py, logout_request.py has also been modified. This is incorrect and only the logout_response.py should point to a response URL. Now all logoutRequest and logoutResponse messages are sent to the slo response URL.

fix for wrong slo url

---

README.md
setup.py
src/onelogin/saml2/xmlparser.py

This removes the dependency on defusedxml by adopting the following classes into `xmlparser.py`:
- `DTDForbidden`
- `EntitiesForbidden`
- `NotSupportedError`
Resolves #233

Remove the dependency on defusedxml

---

src/onelogin/saml2/auth.py

This makes it easier to incorporate other response methods into the
code.
This is part of #237 as well.

Move storing the response data into its own method in the Auth class

---

README.md
src/onelogin/saml2/authn_request.py
src/onelogin/saml2/metadata.py

Add the ability to set the AttributeConsumingServiceIndex in the AuthnRequest.

Attribute consuming service index

---

src/onelogin/saml2/utils.py

We're having an issue where a customer's SSO_URL is set to HTTPS://... and triggers a failure. We're fixing this on our end and I wanted to send the patch upstream as well.

make the redirect scheme matcher case-insensitive.

---

.github/workflows/python-package.yml
Makefile
setup.cfg

This PR:
* adds caching to the CI process
* splits linting and testing; linting is only done on one Python version, so lint/style problems will not cause each versioned test to also fail
* fixes some typos & configuration repetition

CI improvements

---

README.md
demo-django/demo/views.py
demo-flask/index.py
demo-tornado/views.py
demo_pyramid/demo_pyramid/views.py
src/onelogin/saml2/utils.py
tests/src/OneLogin/saml2_tests/response_test.py
tests/src/OneLogin/saml2_tests/utils_test.py

`server_port` is unnecessary, since the HTTP Host header sent by the client already includes any non-standard port. (This is stuffed into `http_host`.)
In addition, when the Python application server is sitting behind a reverse proxy/TLS terminator, SERVER_PORT is likely to be wrong anyway (since it would be the server port of the non-reverse-proxied server).
See https://github.com/onelogin/python3-saml/issues/273#issuecomment-885566427

Deprecate server_port from request data dictionary

---

src/onelogin/saml2/auth.py
src/onelogin/saml2/authn_request.py
src/onelogin/saml2/logout_request.py
src/onelogin/saml2/logout_response.py
src/onelogin/saml2/metadata.py
src/onelogin/saml2/response.py
src/onelogin/saml2/settings.py
tests/src/OneLogin/saml2_tests/authn_request_test.py

This will avoid Python's [class-name-prefix mangling of attributes and methods](https://docs.python.org/3/tutorial/classes.html#private-variables) while still retaining the signal that they're meant for private use of the library.
This makes it easier to e.g. subclass classes should one need to (e.g. as I needed in #212), and to access data from outside (while being mindful of the fact that you're accessing notionally private data).
Only one change to a test was required (and that test was indeed accessing a private field from outside and had to jump through hoops 😄 ).

Replace double-underscored names with single underscores

---

README.md
src/onelogin/saml2/auth.py
src/onelogin/saml2/response.py
tests/src/OneLogin/saml2_tests/auth_test.py

Currently the way of retrieving `IssueInstant` time from the last assertion processed `SAMLResponse` is possible by (please correct me if there's an easier way):
1) Retrieving the XML string by calling `auth.get_last_response_xml()`
2) Parsing the XML document from the XML string using `xml_utils.to_etree()`
3) Querying the last Assertion using `xml_utils.query()`
4) Parsing the SAML2 timestamp using `parse_SAML_to_time()`
Implementing `get_last_assertion_issue_instant()` replaces the four calls above with one.
Why retrieve `IssueInstant`?
There is an odd case where an IdP can send no `notOnOrAfter` within `Conditions` or `SubjectConfirmationData` in an Assertion, as these parameters are both [optional](http://docs.oasis-open.org/security/saml/v2.0/saml-schema-assertion-2.0.xsd). …

Implement get_last_assertion_issue_instant()

---

README.md
src/onelogin/saml2/auth.py
tests/src/OneLogin/saml2_tests/auth_test.py

In an SP initiated flow, last_response_in_response_to() will give flexibility to the developers when performing validation of the SAML Response.
Currently `process_response()` takes in a single response id to compare with the `InResponseTo` value of the response. However, the current `get_last_request_id` function only returns the most recent ID, and this is not very helpful in these cases:
- User A starts SAML authentication process with a SAML request. Before User A completes authentication, User B starts an authentication process, but user A completes their authentication first, sending SAML Response back to the SP. Now, if we call `get_last_request_id` when processing the SAML Response, this will yield the ID of User B's SAML Request.
- To avoid the situation above, we might want to …

Implement Auth.get_last_response_in_response_to()

---

README.md
demo-django/saml/advanced_settings.json
demo-flask/saml/advanced_settings.json
demo-tornado/saml/advanced_settings.json
demo_pyramid/demo_pyramid/saml/advanced_settings.json
src/onelogin/saml2/auth.py
src/onelogin/saml2/constants.py
src/onelogin/saml2/errors.py
src/onelogin/saml2/response.py
src/onelogin/saml2/settings.py
tests/src/OneLogin/saml2_tests/auth_test.py
tests/src/OneLogin/saml2_tests/response_test.py

- Add rejectDeprecatedAlgorithm settings.
- Define DEPRECATED_ALGORITHMS list on Constants. 
- If flag enabled, reject signatures on response, logout_request and logout_response with deprecated algorithm

Support deprecation of sign and digest algorithms

---

setup.py

Version 4.7.0 of lxml was yanked from pypi because it was missing some required data.
Version 4.7.1 replaces it; changing the specifier from `==` to `~=` allows any 4.7.x series lxml.
**EDIT:** I just saw #292 / a55cc9a379da03eff9f96a886f6164fd0792a62e ... has this been reported upstream to lxml?

Don't require yanked version of lxml

---

.travis.yml
README.md
setup.py

The [stats haven't been updated since 2017](https://coveralls.io/github/onelogin/python3-saml?branch=master) so showing a 96% coverage badge is quite deceptive.

Remove coveralls mentions

---

README.md
setup.py
tests/src/OneLogin/saml2_tests/xml_utils_test.py

Add workaroud for the issue lxml version was originally pinned for.
Addresses #292 with a workaround (https://github.com/onelogin/python3-saml/issues/292#issuecomment-1002604291) that does not require pinning lxml version, so newer lxml can be used with CVE vulnerability fixes.
Fixes #319
Untested as I do not have a testcase for the original failure, but I want to use python3-saml without having to downgrade lxml.
For other reports of the underlying issue see also:
https://bugs.launchpad.net/lxml/+bug/1960668
https://mail.python.org/archives/list/lxml@python.org/thread/SCMXQYGN7CQMSPJI3PEW2YBT4YZKNML2/
EDIT: this PR now just removes the version restriction and documents how to avoid the libxml2 version incompatibilities following investigation into cause of the issue, no workarounds

Remove lxml version restriction

---

src/onelogin/saml2/idp_metadata_parser.py
tests/data/metadata/idp_multiple_descriptors.xml
tests/src/OneLogin/saml2_tests/idp_metadata_parser_test.py

Fix WantAuthnRequestsSigned parser. 

---

src/onelogin/saml2/compat.py

Hello there! We've come across some bugs like the following using this library's `add_sign` function:
```
File /opt/virtualenv/monolith/local/lib/python2.7/site-packages/onelogin/saml2/utils.py line 740 in add_sign
elem = OneLogin_Saml2_XML.to_etree(xml)
File /opt/virtualenv/monolith/local/lib/python2.7/site-packages/onelogin/saml2/xml_utils.py line 68 in to_etree
return OneLogin_Saml2_XML._parse_etree(compat.to_bytes(xml), forbid_dtd=True)
File /opt/virtualenv/monolith/local/lib/python2.7/site-packages/onelogin/saml2/compat.py line 42 in to_bytes
return str(data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc9' in position 2593: ordinal not in range(128)
```
It looks like we're getting this error when a user's name or other data has a non-ascii character that goes through …

Handle unicode characters gracefully in python 2

---

README.md
changelog.md
src/onelogin/saml2/utils.py
tests/src/OneLogin/saml2_tests/auth_test.py
tests/src/OneLogin/saml2_tests/response_test.py

As far as I can see the spelling for `ALLOWED` was fixed a long time ago in https://github.com/SAML-Toolkits/python3-saml/commit/0e5ee91f5d24a5b2c8f4f6112520c38c4fe54e1e#diff-36d0f33860b7f3316c66f02d1e9108084362f5693019f987371e0903f8234e8d but the corresponding autogenerated documentation [was not updated](https://github.com/search?q=repo%3ASAML-Toolkits%2Fpython3-saml%20ALOWED&type=code). Can that be regenerated?

Fix spelling in documentation and comments

---

README.md

The previous wording indicated that auth.login() would take some action, whereas it really just returns a URL for you to do something with (redirect or print out).  This clarifies that.

Clarify wording about auth.login in readme

---

src/onelogin/saml2/idp_metadata_parser.py
tests/src/OneLogin/saml2_tests/idp_metadata_parser_test.py

python3-saml urllib dependency responds with 403 status to urls with default Python user-agent

Issue #364: Some urls come with 403 response

---

README.md

It looked like a typo with a trailing semicolon that does not look like it was intended

Fix typo in README.md (?)

---

src/onelogin/saml2/idp_metadata_parser.py
tests/src/OneLogin/saml2_tests/idp_metadata_parser_test.py

Closes #403
Using requests allows us to easily customize the CA_BUNDLE to use when verifying the server certificate, instead of having to disable SSL certificate verification alltogether.

Fetch IDP metadata using requests to support custom server certificates root CAs
